/**
 * Generated by tsnapi — public API snapshot of `@mcbe-mods/ipc`
 */
// #region Interfaces
export interface Chunk {
  id: string;
  seq: number;
  total: number;
  compressed?: true;
  data: string;
}
export interface Deserializer<T> {
  deserialize: (_: string) => T;
}
export interface ErrorResponseData {
  ok: false;
  err: string;
}
export interface HandleOptions<T = never> {
  deserializer?: Deserializer<T>;
}
export interface InvokeOptions<T = never, R = unknown> {
  timeout?: number;
  serializer?: Serializer<T>;
  deserializer?: Deserializer<R>;
}
export interface IPCEvents {
  [EVENTS.ERROR]: Error;
  [EVENTS.INVALID_PACKET]: {
    payload: string;
  };
}
export interface IPCOptions {
  namespace?: string;
  chunkSize?: number;
  compressThreshold?: number;
  maxPacketSize?: number;
  invokeTimeout?: number;
}
export interface OnOptions<T = never> {
  deserializer?: Deserializer<T>;
}
export interface Packet<T = unknown> {
  version: typeof PROTOCOL_VERSION;
  id: string;
  channel: string;
  data: T;
}
export interface ResponseData<T = unknown> {
  ok: true;
  data: T;
}
export interface SendOptions<T = never> {
  serializer?: Serializer<T>;
}
export interface Serializer<T> {
  serialize: (_: T) => string;
}
// #endregion

// #region Classes
export declare class Chunker {
  #private;
  constructor(_: number);
  split(_: string, _: string, _: boolean): Chunk[];
  assemble(_: Chunk): {
    done: false;
  } | {
    done: true;
    data: string;
    compressed: boolean;
  };
  get pendingCount(): number;
}
export declare class Compressor {
  #private;
  constructor(_: number);
  compress(_: string): {
    value: string;
    compressed: boolean;
  };
  decompress(_: string, _: boolean): string;
}
export declare class IPC {
  #private;
  readonly events: EventEmitter<IPCEvents>;
  constructor(_?: IPCOptions);
  dispose(): void;
  send(_: string): void;
  send<T>(_: string, _: T): void;
  send<T>(_: string, _: T, _: SendOptions<T>): void;
  on<T>(_: string, _: (_: T) => void): () => void;
  on<T>(_: string, _: (_: T) => void, _: OnOptions<T>): () => void;
  invoke<R = unknown>(_: string): Promise<R>;
  invoke<R = unknown>(_: string, _: InvokeOptions<never, R>): Promise<R>;
  invoke<T = never, R = unknown>(_: string, _: T, _?: InvokeOptions<T, R>): Promise<R>;
  handle<T, R>(_: string, _: (_: T) => R | Promise<R>): () => void;
  handle<T, R>(_: string, _: (_: T) => R | Promise<R>, _: HandleOptions<T>): () => void;
}
export declare class Transport {
  #private;
  constructor(_: string);
  send(_: string, _: string, _: string): void;
  onReceive(_: (_: string, _: string, _: string) => void): () => void;
}
// #endregion

// #region Variables
export declare const EVENTS: {
  readonly ERROR: "error";
  readonly INVALID_PACKET: "invalid-packet";
};
export declare const PROTOCOL_VERSION: 1;
// #endregion