/**
 * Generated by tsnapi — public API snapshot of `@mcbe-mods/ipc`
 */
// #region Interfaces
export interface Chunk {
  i: string;
  s: number;
  t: number;
  c?: 1;
  d: string;
}
export interface Deserializer<T> {
  deserialize: (_: string) => T;
}
export interface ErrorResponseData {
  ok: false;
  err: string;
}
export interface IPCOptions {
  namespace?: string;
  chunkSize?: number;
  compressThreshold?: number;
  chunkTimeout?: number;
  maxPacketSize?: number;
}
export interface IPCSystemEvents {
  'error': Error;
  'chunk:timeout': {
    id: string;
  };
}
export interface Packet<T = unknown> {
  v: 1;
  id: string;
  e: string;
  d: T;
}
export interface ResponseData<T = unknown> {
  ok: true;
  data: T;
}
export interface Serializer<T> {
  serialize: (_: T) => string;
}
// #endregion

// #region Classes
export declare class Chunker {
  #private;
  constructor(_: number, _: number);
  split(_: string, _: string, _: boolean): Chunk[];
  assemble(_: Chunk): {
    done: false;
  } | {
    done: true;
    data: string;
    compressed: boolean;
  };
  get pendingCount(): number;
}
export declare class Compressor {
  #private;
  constructor(_: number);
  compress(_: string): {
    value: string;
    compressed: boolean;
  };
  decompress(_: string, _: boolean): string;
}
export declare class IPC {
  #private;
  readonly events: EventEmitter<IPCSystemEvents>;
  constructor(_?: IPCOptions);
  send<T>(_: string, _: NoInfer<T>): void;
  send<T>(_: string, _: Serializer<T>, _: NoInfer<T>): void;
  on<T>(_: string, _: (_: T) => void): () => void;
  on<T>(_: string, _: Deserializer<T>, _: (_: T) => void): () => void;
  invoke<T = unknown, R = unknown>(_: string, _: T): Promise<R>;
  invoke<T = unknown, R = unknown>(_: string, _: Serializer<T>, _: Deserializer<R>, _: T): Promise<R>;
  handle<T, R>(_: string, _: (_: T) => R | Promise<R>): () => void;
}
export declare class Transport {
  #private;
  constructor(_: string);
  send(_: string): void;
  onReceive(_: (_: string) => void): () => void;
}
// #endregion